version: "3.7"

services:
  mysql-test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=task_tracking_1_test
    ports:
      - 3308:3306
    networks:
      - task_tracking_1

networks:
  task_tracking_1:
    driver: bridge
