name: "Main pipeline"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - name: Linter
        uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          npmInstall: false

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run docker compose
        run: |
          docker-compose -f docker-compose.test.yml up -d
          docker ps

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Push to dockerhub
        if: github.ref == 'refs/heads/main'
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: poorlydefinedbehaviour/task_tracking_1
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
